### ISSUE TITLE
Golden files named with super class regardless of settings.

### ISSUE THREAD

**Issue by javydreamercsw** [retest/recheck-web#463] opened 2019-12-13 15:14 UTC
### Describe the Bug
On version 1.7.0 the golden files are named differently. They use a superclass instead of the actual test class rendering old golden files invalid. It doesn't matter how do you specify the value. This is similar to https://github.com/retest/recheck-web/issues/418

### How to Reproduce?

1. Configure the driver as follows:
```
new RecheckDriver(
            (RemoteWebDriver) getSeleniumInterface().getWebDriver(),
            RecheckOptions.builder().suiteName(getClass().getName()).build());
```

1. Run test with 1.7.0 to create golden files.

1. Debug the test and see the right values passed to the Recheck code but ignored at run time.

### Setup
recheck-web: 1.7.0
Selenium version: 3.141.59
Testing framework: TestNG 7.0.0
OS: MacOS 14
Java version: OpenJDK 11

**Comment by diba1013** [comment] 2019-12-13 18:38
Thanks for the details. I will take a look at this on Monday.

**Comment by diba1013** [comment] 2019-12-16 08:38
I trew together some tests, similar to those from [last time](https://github.com/retest/recheck-web/issues/418#issuecomment-552461530).

#### Setup:

1. Windows 10
1. OpenJDK 11
1. Maven 3.6.0
1. TestNG 7.0.0
1. Selenium 3.141.59
1. recheck-web 1.7.0

### Tests

```java
public class HomeTest extends BaseTest {

	@Test
	public void test() {
		driver.startTest();
		driver.get( "https://google.com" );
		driver.capTest();
	}
}
```

And two instances of `BaseTest`

```java
public class BaseTest {

	protected RecheckDriver driver;

	@BeforeMethod(alwaysRun = true)
	public void setUp() {
		driver = new RecheckDriver( WebDriverFactory.createChromeDriver(), RecheckOptions.builder() //
				.suiteName( getClass().getName() ) //
				.build() );
	}

	@AfterMethod( alwaysRun = true )
	public void tearDown() {
		driver.quit();
	}
}
```

```java
public class BaseTest {

	protected RecheckDriver driver = new RecheckDriver( WebDriverFactory.createChromeDriver(), RecheckOptions.builder() //
			.suiteName( getClass().getName() ) //
			.build() );

	@AfterMethod( alwaysRun = true )
	public void tearDown() {
		driver.quit();
	}
}
```

### Conclusions

Both tests executed with the following `AssertionError`

```log
java.lang.AssertionError: 'com.example.recheck.HomeTest': No Golden Master found. First time test was run? Created new Golden Master, so don't forget to commit...
	src\test\resources\retest\recheck\com.example.recheck.HomeTest\test.00.recheck
```

So from my point of view, everything works as expected. Therefore I did not debug though the code.

### Questions

Did you do anything different than me with regards of setting up the test? E.g.:

* Where do you instantiate the `RecheckDriver` within the super class as field, a specialized `@BeforeMethod`, ...?
* Do you properly call the lifecycle methods? You might want to check out the [testng-extension](https://github.com/retest/recheck-testng-extension).
* Did you exclude potential maven dependency resolving?

It would be very helpful, if you could provide such a minimal test where this problem occurs.

**Comment by javydreamercsw** [comment] 2019-12-16 20:42
Looking into this to see difference sin code and try to figure out what's different.

**Comment by diba1013** [comment] 2019-12-16 20:45
Sure, if you want I can provide you the whole project.

**Comment by javydreamercsw** [comment] 2019-12-16 21:09
Seems to work now with the code above. I was using RecheckWebImpl and it's check methods before and something just didn't work the same.

**Comment by diba1013** [comment] 2019-12-17 07:27
There are [two ways of using recheck-web](https://docs.retest.de/recheck-web/ways-of-using-recheck-web/):

1. Explicit checking: You create a `RecheckImpl` (or `RecheckWebImpl`) and explicitly call `check` with a `WebDriver`. This driver can be an ordinary `ChromeDriver` or a `UnbreakableDriver`.
2. Implicit checking: You have a wrapped driver (e.g. `RecheckDriver`) which has a `RecheckWebImpl` already integrated. It will call `check` from within the driver functions (e.g. `driver.getElement(by).click()`), which will create a Golden Master for the click action.

Mixing both strategies (i.e. dropping a `RecheckDriver` into `Recheck#check` explicitly) is not supported and will result in unexpected behavior. Since such a problem already occurred a few times, we are trying to come up with a way to warn the user if such a thing happens. However, this is not that straight forward, since we need to distinguish between internal and external usage, as we ourselves, internally, drop a `RecheckDriver` into the `RecheckWebImpl`.

Since your problem seems now to be resolved.

**Closed by diba1013** 2019-12-17 07:27 UTC
Labels: bug
